---
driver:
  name: vagrant
  vm_hostname: opencontrail.ci.local
  use_sudo: false
  customize:
    memory: 512


provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  formula: opencontrail
  #dependencies:
    #- { name: 'linux',  path: '../../tcpcloud/linux'}
  log_level: info
  state_top:
    base:
      "*":
        - opencontrail
  pillars:
    linux.sls:
      linux:
        system:
          name: opencontrail.ci.local
        network:
          interface:
            vhost0:
              enabled: True
    top.sls:
      base:
        "*":
          - opencontrail
          - linux
  grains:
    noservices: False


verifier:
  name: inspec
  sudo: true


platforms:

  # NOTE: on oc 2.22 some of the converge tests fails - as we are focused now to 3.x will keep it ootb commented
  #
  #- name: ubuntu-14.04-oc2
  #  # NOTE, workaround for dependencies until kitchen salt will install SPM/PKG dependencies
  #  driver:
  #    provision_command:
  #    - apt-get install -y wget
  #    - wget -O - http://apt.tcpcloud.eu/public.gpg | sudo apt-key add -
  #    - echo "deb http://apt.tcpcloud.eu/nightly/ trusty main security extra tcp tcp-salt oc222 liberty" > /etc/apt/sources.list
  #    - apt-get update
  #    - apt-get install -y salt-minion salt-formula-linux
  - name: ubuntu-14.04
    # NOTE, workaround for dependencies until kitchen salt will install SPM/PKG dependencies
    driver:
      provision_command:
      - apt-get install -y wget
      - wget -O - http://apt.tcpcloud.eu/public.gpg | sudo apt-key add -
      - echo "deb http://apt.tcpcloud.eu/nightly/ trusty main security extra tcp tcp-salt oc30 liberty" > /etc/apt/sources.list
      - apt-get update
      - apt-get install -y salt-minion salt-formula-linux

  # FIXME, on xenial converge fails, missing packages etc..
  #
  #- name: ubuntu-16.04
  #  # NOTE, workaround for dependencies until kitchen salt will install SPM/PKG dependencies
  #  driver:
  #    provision_command:
  #    - apt-get install -y wget
  #    - wget -O - http://apt.tcpcloud.eu/public.gpg | sudo apt-key add -
  #    - echo "deb http://apt.tcpcloud.eu/nightly/ trusty main security extra tcp tcp-salt oc30 liberty" > /etc/apt/sources.list
  #    - apt-get update
  #    - apt-get install -y salt-minion salt-formula-linux
  #  name: ubuntu-16.04-mitaka
  #  # NOTE, workaround for dependencies until kitchen salt will install SPM/PKG dependencies
  #  driver:
  #    provision_command:
  #    - apt-get install -y wget
  #    - wget -O - http://apt.tcpcloud.eu/public.gpg | sudo apt-key add -
  #    - echo "deb http://apt.tcpcloud.eu/nightly/ trusty main security extra tcp tcp-salt oc30 mitaka" > /etc/apt/sources.list
  #    - apt-get update
  #    - apt-get install -y salt-minion salt-formula-linux

  #- name: centos-7.1

suites:

  - name: analytics
    provisioner:
      pillars-from-files:
        opencontrail.sls: tests/pillar/analytics.sls

  - name: cluster
    provisioner:
      pillars-from-files:
        opencontrail.sls: tests/pillar/cluster.sls

  - name: control
    provisioner:
      pillars-from-files:
        opencontrail.sls: tests/pillar/control.sls

  - name: single
    provisioner:
      pillars-from-files:
        opencontrail.sls: tests/pillar/single.sls

  - name: tor
    provisioner:
      pillars-from-files:
        opencontrail.sls: tests/pillar/tor.sls

  - name: vrouter_kubernetes
    provisioner:
      pillars-from-files:
        opencontrail.sls: tests/pillar/vrouter_kubernetes.sls

  - name: vrouter
    provisioner:
      pillars-from-files:
        opencontrail.sls: tests/pillar/vrouter.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
